### ISSUE TITLE
Error while sending to multiple addresses

### ISSUE THREAD

**Issue by burlakko** [ijsto/strapi-provider-email-mailjet#2]
Sending to an array of email addresses gives an error.
Error: Unsuccessful: 400 Type mismatch. Expected type "string".

**Comment by ScottAgirs** [comment]
Hey @burlakko thank you for opening this and for your input!

With the [Release 3.3.0](https://github.com/ijsto/strapi-provider-email-mailjet/releases/tag/3.3.0) this is addressed and should fix this use case. Thanks again!

Closing this, feel free to re-open if any issues.
