### ISSUE TITLE
[New API Method] Update specific contact's contactdata

### ISSUE THREAD

**Issue by rkrueger11** [ijsto/strapi-provider-email-mailjet#4]
Would love to add a name for each of my contacts to personalize the emails.

https://dev.mailjet.com/email/reference/contacts/contact-properties#v3_put_contactdata_contact_ID

**Comment by ScottAgirs** [comment]
Hey @rkrueger11 thanks for the feature request! Would you be interested in taking a stab at a PR for this?

**Comment by ScottAgirs** [comment]
@rkrueger11 quick heads up - will consider this for next major update. Feel free to ping if this is urgent.

**Comment by rkrueger11** [comment]
Hey @ScottAgirs, any idea when you think you might get to the next major update? I'll try to submit a PR for this too if I get the time - currently trying to also launch a new blog.

**Comment by ScottAgirs** [comment]
Hey @rkrueger11 sorry for the late response. I shd correct myself, not major - rather minor release. :)

Aiming for the next week, if not then definitely before Christmas break. Have a couple more features in the pipeline that would be to batch-in in the same release.

But lmk if this is urgent for you, if you have a PR that will be working can also just do a patch : )

**Comment by ScottAgirs** [comment]
Hey, @rkrueger11. updateContact() has been added with v3.5.0 - please see if this solves your use case.

Sorry for the delay and please feel free to re-open if anything.
